### ISSUE TITLE
Other dependencies

### ISSUE THREAD

**Issue by triplingual** [UniTasLibrary/populate_omeka_s_site#1]
After running `pip install -r requirements.txt` I still got errors for `requests` and `config` and had to `pip install` them also. Probably not common to not have those, but I didn't.

**Comment by goetzk** [comment]
Hi,
I've added requests to requirements.txt in ba1c134. Based on your comment in #2 I think there is some confusion about `config` - I will follow up the other part over in that issue.

thanks for bringing this to our attention.
Karl.
