### ISSUE TITLE
config module can't find config file

### ISSUE THREAD

**Issue by triplingual** [UniTasLibrary/populate_omeka_s_site#2]
Not sure whether it's me, but I get an error right of the bat when running:
```
Traceback (most recent call last):
  File "html_site_to_omeka_s.py", line 189, in <module>
    main_site_migration()
  File "html_site_to_omeka_s.py", line 21, in main_site_migration
    all_website_files = os.walk(config.website_root_on_disk)
AttributeError: 'module' object has no attribute 'website_root_on_disk'
```

I can't see where `config` knows which file is the config file, and [module documentation](http://www.red-dove.com/config-doc/#simple-usage) suggests it needs to be told directly, as best as I read it quickly.

**Comment by goetzk** [comment]
Hi @triplingual ,
`config` is not a module which should be installed in the project but rather the projects own configuration file config.py which you are expected to create. A config.py.example is shipped which you can use as a template.
I gather the configuration section in README.rst did not make this clear so if you'd like to suggest some improved words i'd be happy to update it.

thanks,
Karl.

**Comment by triplingual** [comment]
@goetzk I did get asked to install `config` when I ran the requirements install, but the problem of the script not finding my config file turned out to be my own fault. (Story of having two copies of the script files and executing from the wrong copy.)

**Comment by triplingual** [comment]
Just tested, and `pip unintall config` doesn't prevent the script from running, as you suggest. I don't know enough Python to know why requirements asked me to install it if it's not needed.

(Alternately, maybe my sub-optimal local dev environment has multiple Python 2.7 options and `pip uninstall` is not addressing the right one)

**Comment by goetzk** [comment]
Hi,
I've just made a clean python 2.7 virtualenvironment , cloned the repository and run `pip install -r requirements.txt`. config is not pulled in or suggested. I'm not sure why it prompted you - its very strange.

I'm going to resolve this as unreproducable but if it happens again / you can supply more information I'm happy to try and help.

Karl.
